const ONE_SECOND=1000
const ONE_MINUTE=ONE_SECOND*60
const ONE_HOUR=ONE_MINUTE*60
const ONE_DAY=ONE_HOUR*24
const ONE_WEEK=ONE_DAY*7
const ONE_MONTH=ONE_DAY*30
const ONE_YEAR=ONE_DAY*365

const USER_COOKIE_VALIDITY=ONE_YEAR*50